site_name: Solution Catalog Python client
nav:
  - Home: index.md
  - Documentation for API Endpoints: endpoints/index.md 
theme: 
  name: material
  logo: 'logo.png'

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
